export const ActionTypes = {
    //drawer
    OPEN_DRAWER: "OPEN_DRAWER",
    RESET_DRAWER: "RESET_DRAWER",
    //transactions
    GET_TRANSACTIONS: "GET_TRANSACTIONS",
    GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
    GET_TRANSACTIONS_FAILURE: "GET_TRANSACTIONS_FAILURE",
    GET_TRANSACTION_DETAILS: "GET_TRANSACTION_DETAILS",
    GET_TRANSACTION_DETAILS_SUCCESS: "GET_TRANSACTION_DETAILS_SUCCESS",
    GET_TRANSACTION_DETAILS_FAILURE: "GET_TRANSACTION_DETAILS_FAILURE",
    REMOVE_TRANSACTION_DETAILS: "REMOVE_TRANSACTION_DETAILS",
    UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
    UPDATE_TRANSACTION_SUCCESS: "UPDATE_TRANSACTION_SUCCESS",
    UPDATE_TRANSACTION_FAILURE: "UPDATE_TRANSACTION_FAILURE",
    //users
    GET_USERS: "GET_USERS",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",
    GET_USER_DETAILS: "GET_USER_DETAILS",
    GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",
    REMOVE_USER_DETAILS: "REMOVE_USER_DETAILS",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};