export const ActionTypes = {
    OPEN_DRAWER: "OPEN_DRAWER",
    RESET_DRAWER: "RESET_DRAWER",
    GET_TRANSACTIONS: "GET_TRANSACTIONS",
    GET_TRANSACTIONS_REQUEST: "GET_TRANSACTIONS_REQUEST",
    GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
    GET_TRANSACTIONS_FAILURE: "GET_TRANSACTIONS_FAILURE",
    UPDATE_TRANSACTION_REQUEST: "UPDATE_TRANSACTION_REQUEST",
    UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
    UPDATE_TRANSACTION_SUCCESS: "UPDATE_TRANSACTION_SUCCESS",
    UPDATE_TRANSACTION_FAILURE: "UPDATE_TRANSACTION_FAILURE",
    SELECTED_TRANSACTION: "SELECTED_TRANSACTION",
    REMOVE_SELECTED_TRANSACTION: "REMOVE_SELECTED_TRANSACTION",
    REMOVE_UPDATED_TRANSACTION: "REMOVE_UPDATED_TRANSACTION"
};