export const ActionTypes = {
    //transactions
    OPEN_DRAWER: "OPEN_DRAWER",
    RESET_DRAWER: "RESET_DRAWER",
    GET_TRANSACTIONS: "GET_TRANSACTIONS",
    GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
    GET_TRANSACTIONS_FAILURE: "GET_TRANSACTIONS_FAILURE",
    UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
    UPDATE_TRANSACTION_SUCCESS: "UPDATE_TRANSACTION_SUCCESS",
    UPDATE_TRANSACTION_FAILURE: "UPDATE_TRANSACTION_FAILURE",
    SELECTED_TRANSACTION: "SELECTED_TRANSACTION",
    REMOVE_SELECTED_TRANSACTION: "REMOVE_SELECTED_TRANSACTION",
    //users
    GET_USERS: "GET_USERS",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
    SELECTED_USER: "SELECTED_USER",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
};