export const ActionTypes = {
    OPEN_DRAWER: "OPEN_DRAWER",
    RESET_DRAWER: "RESET_DRAWER",
    GET_TRANSACTIONS: "GET_TRANSACTIONS",
    SET_TRANSACTIONS: "SET_TRANSACTIONS",
    SELECTED_TRANSACTION: "SELECTED_TRANSACTION",
    EDIT_TRANSACTION: "EDIT_TRANSACTION",
};